# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e7c0f001ed351035867ec167d9e0ae1e547c37b1b7f19fcb463e2fe4ca23c5e0cb6140ef57743a3f3afec2c0b1da119097f8fd1d420f2bfc892fde6fe33fc6f

test:
  secret_key_base: e27c9691c073991db9fbc203527641270b238b1c0751c121d08ad92875a2b6314bae5f0a76bdedf1d660d6f830bb598f25ee3270d678ab62c9076164c470e7f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
